// <auto-generated />
using MANAJEMEN_RESTORAN_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MANAJEMEN_RESTORAN_API.Migrations
{
    [DbContext(typeof(RestoDbContext))]
    [Migration("20241225034752_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHCabang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JumlahLantai")
                        .HasColumnType("int");

                    b.Property<string>("Kota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MHCabangs");
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MHCustomers");
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Lantai")
                        .HasColumnType("int");

                    b.Property<int>("NomorMeja")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("isReserved")
                        .HasColumnType("bit");

                    b.Property<int>("mhCabangId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("mhCabangId");

                    b.ToTable("MHTables");
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHTable", b =>
                {
                    b.HasOne("MANAJEMEN_RESTORAN_API.Models.Domain.MHCabang", "MHCabang")
                        .WithMany()
                        .HasForeignKey("mhCabangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MHCabang");
                });
#pragma warning restore 612, 618
        }
    }
}
