// <auto-generated />
using MANAJEMEN_RESTORAN_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MANAJEMEN_RESTORAN_API.Migrations
{
    [DbContext(typeof(RestoDbContext))]
    [Migration("20241225040828_cabang")]
    partial class cabang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHCabang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JumlahLantai")
                        .HasColumnType("int");

                    b.Property<string>("Kota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MHCabangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JumlahLantai = 1,
                            Kota = "Surabaya",
                            Name = "CABANG 1"
                        },
                        new
                        {
                            Id = 2,
                            JumlahLantai = 2,
                            Kota = "Sidoarjo",
                            Name = "CABANG 2"
                        },
                        new
                        {
                            Id = 3,
                            JumlahLantai = 1,
                            Kota = "Gresik",
                            Name = "CABANG 3"
                        },
                        new
                        {
                            Id = 4,
                            JumlahLantai = 2,
                            Kota = "Surabaya",
                            Name = "CABANG 4"
                        },
                        new
                        {
                            Id = 5,
                            JumlahLantai = 1,
                            Kota = "Sidoarjo",
                            Name = "CABANG 5"
                        },
                        new
                        {
                            Id = 6,
                            JumlahLantai = 2,
                            Kota = "Gresik",
                            Name = "CABANG 6"
                        },
                        new
                        {
                            Id = 7,
                            JumlahLantai = 1,
                            Kota = "Surabaya",
                            Name = "CABANG 7"
                        },
                        new
                        {
                            Id = 8,
                            JumlahLantai = 2,
                            Kota = "Sidoarjo",
                            Name = "CABANG 8"
                        },
                        new
                        {
                            Id = 9,
                            JumlahLantai = 1,
                            Kota = "Gresik",
                            Name = "CABANG 9"
                        },
                        new
                        {
                            Id = 10,
                            JumlahLantai = 2,
                            Kota = "Surabaya",
                            Name = "CABANG 10"
                        });
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MHCustomers");
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Lantai")
                        .HasColumnType("int");

                    b.Property<int>("NomorMeja")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("isReserved")
                        .HasColumnType("bit");

                    b.Property<int>("mhCabangId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("mhCabangId");

                    b.ToTable("MHTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Lantai = 1,
                            NomorMeja = 1,
                            Status = 0,
                            isReserved = false,
                            mhCabangId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 6,
                            Lantai = 1,
                            NomorMeja = 2,
                            Status = 1,
                            isReserved = false,
                            mhCabangId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2,
                            Lantai = 2,
                            NomorMeja = 3,
                            Status = 0,
                            isReserved = false,
                            mhCabangId = 2
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Lantai = 2,
                            NomorMeja = 4,
                            Status = 1,
                            isReserved = false,
                            mhCabangId = 2
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 8,
                            Lantai = 1,
                            NomorMeja = 5,
                            Status = 0,
                            isReserved = false,
                            mhCabangId = 3
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            Lantai = 1,
                            NomorMeja = 6,
                            Status = 1,
                            isReserved = false,
                            mhCabangId = 3
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6,
                            Lantai = 2,
                            NomorMeja = 7,
                            Status = 0,
                            isReserved = false,
                            mhCabangId = 4
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            Lantai = 2,
                            NomorMeja = 8,
                            Status = 1,
                            isReserved = false,
                            mhCabangId = 4
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 4,
                            Lantai = 1,
                            NomorMeja = 9,
                            Status = 0,
                            isReserved = false,
                            mhCabangId = 5
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 8,
                            Lantai = 1,
                            NomorMeja = 10,
                            Status = 1,
                            isReserved = false,
                            mhCabangId = 5
                        });
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHTable", b =>
                {
                    b.HasOne("MANAJEMEN_RESTORAN_API.Models.Domain.MHCabang", "MHCabang")
                        .WithMany("MHTables")
                        .HasForeignKey("mhCabangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MHCabang");
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHCabang", b =>
                {
                    b.Navigation("MHTables");
                });
#pragma warning restore 612, 618
        }
    }
}
