// <auto-generated />
using MANAJEMEN_RESTORAN_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MANAJEMEN_RESTORAN_API.Migrations
{
    [DbContext(typeof(RestoDbContext))]
    [Migration("20241220145532_seed_mh_table")]
    partial class seed_mh_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHCabang", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("jumlah_lantai")
                        .HasColumnType("int");

                    b.Property<string>("kota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mh_cabang", "dbo");
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHCustomer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mh_customer", "dbo");
                });

            modelBuilder.Entity("MANAJEMEN_RESTORAN_API.Models.Domain.MHTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<int>("id_mh_cabang")
                        .HasColumnType("int");

                    b.Property<bool>("is_reserved")
                        .HasColumnType("bit");

                    b.Property<int>("lantai")
                        .HasColumnType("int");

                    b.Property<int>("nomor_meja")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("mh_table", "dbo");

                    b.HasData(
                        new
                        {
                            id = 1,
                            capacity = 4,
                            id_mh_cabang = 1,
                            is_reserved = false,
                            lantai = 1,
                            nomor_meja = 1,
                            status = 0
                        },
                        new
                        {
                            id = 2,
                            capacity = 4,
                            id_mh_cabang = 1,
                            is_reserved = false,
                            lantai = 1,
                            nomor_meja = 2,
                            status = 0
                        },
                        new
                        {
                            id = 3,
                            capacity = 3,
                            id_mh_cabang = 1,
                            is_reserved = false,
                            lantai = 1,
                            nomor_meja = 3,
                            status = 0
                        },
                        new
                        {
                            id = 4,
                            capacity = 3,
                            id_mh_cabang = 2,
                            is_reserved = false,
                            lantai = 1,
                            nomor_meja = 8,
                            status = 0
                        },
                        new
                        {
                            id = 5,
                            capacity = 3,
                            id_mh_cabang = 2,
                            is_reserved = false,
                            lantai = 1,
                            nomor_meja = 10,
                            status = 0
                        },
                        new
                        {
                            id = 6,
                            capacity = 2,
                            id_mh_cabang = 2,
                            is_reserved = false,
                            lantai = 1,
                            nomor_meja = 9,
                            status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
